// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: ai.proto
// Protobuf Java Version: 4.30.2

package com.github.achrafmataich.fashion_mnist_backend.grpc;

public final class Ai {
  private Ai() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 30,
      /* patch= */ 2,
      /* suffix= */ "",
      Ai.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ImageRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ai.ImageRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string image = 1;</code>
     * @return The image.
     */
    java.lang.String getImage();
    /**
     * <code>string image = 1;</code>
     * @return The bytes for image.
     */
    com.google.protobuf.ByteString
        getImageBytes();
  }
  /**
   * Protobuf type {@code ai.ImageRequest}
   */
  public static final class ImageRequest extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:ai.ImageRequest)
      ImageRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 30,
        /* patch= */ 2,
        /* suffix= */ "",
        ImageRequest.class.getName());
    }
    // Use ImageRequest.newBuilder() to construct.
    private ImageRequest(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private ImageRequest() {
      image_ = "";
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.github.achrafmataich.fashion_mnist_backend.grpc.Ai.internal_static_ai_ImageRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.github.achrafmataich.fashion_mnist_backend.grpc.Ai.internal_static_ai_ImageRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.github.achrafmataich.fashion_mnist_backend.grpc.Ai.ImageRequest.class, com.github.achrafmataich.fashion_mnist_backend.grpc.Ai.ImageRequest.Builder.class);
    }

    public static final int IMAGE_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private volatile java.lang.Object image_ = "";
    /**
     * <code>string image = 1;</code>
     * @return The image.
     */
    @java.lang.Override
    public java.lang.String getImage() {
      java.lang.Object ref = image_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        image_ = s;
        return s;
      }
    }
    /**
     * <code>string image = 1;</code>
     * @return The bytes for image.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getImageBytes() {
      java.lang.Object ref = image_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        image_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(image_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 1, image_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(image_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(1, image_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.github.achrafmataich.fashion_mnist_backend.grpc.Ai.ImageRequest)) {
        return super.equals(obj);
      }
      com.github.achrafmataich.fashion_mnist_backend.grpc.Ai.ImageRequest other = (com.github.achrafmataich.fashion_mnist_backend.grpc.Ai.ImageRequest) obj;

      if (!getImage()
          .equals(other.getImage())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + IMAGE_FIELD_NUMBER;
      hash = (53 * hash) + getImage().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.github.achrafmataich.fashion_mnist_backend.grpc.Ai.ImageRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.github.achrafmataich.fashion_mnist_backend.grpc.Ai.ImageRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.github.achrafmataich.fashion_mnist_backend.grpc.Ai.ImageRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.github.achrafmataich.fashion_mnist_backend.grpc.Ai.ImageRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.github.achrafmataich.fashion_mnist_backend.grpc.Ai.ImageRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.github.achrafmataich.fashion_mnist_backend.grpc.Ai.ImageRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.github.achrafmataich.fashion_mnist_backend.grpc.Ai.ImageRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.github.achrafmataich.fashion_mnist_backend.grpc.Ai.ImageRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.github.achrafmataich.fashion_mnist_backend.grpc.Ai.ImageRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static com.github.achrafmataich.fashion_mnist_backend.grpc.Ai.ImageRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.github.achrafmataich.fashion_mnist_backend.grpc.Ai.ImageRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.github.achrafmataich.fashion_mnist_backend.grpc.Ai.ImageRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.github.achrafmataich.fashion_mnist_backend.grpc.Ai.ImageRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ai.ImageRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ai.ImageRequest)
        com.github.achrafmataich.fashion_mnist_backend.grpc.Ai.ImageRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.github.achrafmataich.fashion_mnist_backend.grpc.Ai.internal_static_ai_ImageRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.github.achrafmataich.fashion_mnist_backend.grpc.Ai.internal_static_ai_ImageRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.github.achrafmataich.fashion_mnist_backend.grpc.Ai.ImageRequest.class, com.github.achrafmataich.fashion_mnist_backend.grpc.Ai.ImageRequest.Builder.class);
      }

      // Construct using ai.Ai.ImageRequest.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        image_ = "";
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.github.achrafmataich.fashion_mnist_backend.grpc.Ai.internal_static_ai_ImageRequest_descriptor;
      }

      @java.lang.Override
      public com.github.achrafmataich.fashion_mnist_backend.grpc.Ai.ImageRequest getDefaultInstanceForType() {
        return com.github.achrafmataich.fashion_mnist_backend.grpc.Ai.ImageRequest.getDefaultInstance();
      }

      @java.lang.Override
      public com.github.achrafmataich.fashion_mnist_backend.grpc.Ai.ImageRequest build() {
        com.github.achrafmataich.fashion_mnist_backend.grpc.Ai.ImageRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.github.achrafmataich.fashion_mnist_backend.grpc.Ai.ImageRequest buildPartial() {
        com.github.achrafmataich.fashion_mnist_backend.grpc.Ai.ImageRequest result = new com.github.achrafmataich.fashion_mnist_backend.grpc.Ai.ImageRequest(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(com.github.achrafmataich.fashion_mnist_backend.grpc.Ai.ImageRequest result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.image_ = image_;
        }
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.github.achrafmataich.fashion_mnist_backend.grpc.Ai.ImageRequest) {
          return mergeFrom((com.github.achrafmataich.fashion_mnist_backend.grpc.Ai.ImageRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.github.achrafmataich.fashion_mnist_backend.grpc.Ai.ImageRequest other) {
        if (other == com.github.achrafmataich.fashion_mnist_backend.grpc.Ai.ImageRequest.getDefaultInstance()) return this;
        if (!other.getImage().isEmpty()) {
          image_ = other.image_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                image_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.lang.Object image_ = "";
      /**
       * <code>string image = 1;</code>
       * @return The image.
       */
      public java.lang.String getImage() {
        java.lang.Object ref = image_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          image_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string image = 1;</code>
       * @return The bytes for image.
       */
      public com.google.protobuf.ByteString
          getImageBytes() {
        java.lang.Object ref = image_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          image_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string image = 1;</code>
       * @param value The image to set.
       * @return This builder for chaining.
       */
      public Builder setImage(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        image_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>string image = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearImage() {
        image_ = getDefaultInstance().getImage();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>string image = 1;</code>
       * @param value The bytes for image to set.
       * @return This builder for chaining.
       */
      public Builder setImageBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        image_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:ai.ImageRequest)
    }

    // @@protoc_insertion_point(class_scope:ai.ImageRequest)
    private static final com.github.achrafmataich.fashion_mnist_backend.grpc.Ai.ImageRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.github.achrafmataich.fashion_mnist_backend.grpc.Ai.ImageRequest();
    }

    public static com.github.achrafmataich.fashion_mnist_backend.grpc.Ai.ImageRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ImageRequest>
        PARSER = new com.google.protobuf.AbstractParser<ImageRequest>() {
      @java.lang.Override
      public ImageRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<ImageRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ImageRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.github.achrafmataich.fashion_mnist_backend.grpc.Ai.ImageRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface PredictionReplyOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ai.PredictionReply)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string prediction = 1;</code>
     * @return The prediction.
     */
    java.lang.String getPrediction();
    /**
     * <code>string prediction = 1;</code>
     * @return The bytes for prediction.
     */
    com.google.protobuf.ByteString
        getPredictionBytes();
  }
  /**
   * Protobuf type {@code ai.PredictionReply}
   */
  public static final class PredictionReply extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:ai.PredictionReply)
      PredictionReplyOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 30,
        /* patch= */ 2,
        /* suffix= */ "",
        PredictionReply.class.getName());
    }
    // Use PredictionReply.newBuilder() to construct.
    private PredictionReply(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private PredictionReply() {
      prediction_ = "";
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.github.achrafmataich.fashion_mnist_backend.grpc.Ai.internal_static_ai_PredictionReply_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.github.achrafmataich.fashion_mnist_backend.grpc.Ai.internal_static_ai_PredictionReply_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.github.achrafmataich.fashion_mnist_backend.grpc.Ai.PredictionReply.class, com.github.achrafmataich.fashion_mnist_backend.grpc.Ai.PredictionReply.Builder.class);
    }

    public static final int PREDICTION_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private volatile java.lang.Object prediction_ = "";
    /**
     * <code>string prediction = 1;</code>
     * @return The prediction.
     */
    @java.lang.Override
    public java.lang.String getPrediction() {
      java.lang.Object ref = prediction_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        prediction_ = s;
        return s;
      }
    }
    /**
     * <code>string prediction = 1;</code>
     * @return The bytes for prediction.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getPredictionBytes() {
      java.lang.Object ref = prediction_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        prediction_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(prediction_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 1, prediction_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(prediction_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(1, prediction_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.github.achrafmataich.fashion_mnist_backend.grpc.Ai.PredictionReply)) {
        return super.equals(obj);
      }
      com.github.achrafmataich.fashion_mnist_backend.grpc.Ai.PredictionReply other = (com.github.achrafmataich.fashion_mnist_backend.grpc.Ai.PredictionReply) obj;

      if (!getPrediction()
          .equals(other.getPrediction())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + PREDICTION_FIELD_NUMBER;
      hash = (53 * hash) + getPrediction().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.github.achrafmataich.fashion_mnist_backend.grpc.Ai.PredictionReply parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.github.achrafmataich.fashion_mnist_backend.grpc.Ai.PredictionReply parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.github.achrafmataich.fashion_mnist_backend.grpc.Ai.PredictionReply parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.github.achrafmataich.fashion_mnist_backend.grpc.Ai.PredictionReply parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.github.achrafmataich.fashion_mnist_backend.grpc.Ai.PredictionReply parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.github.achrafmataich.fashion_mnist_backend.grpc.Ai.PredictionReply parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.github.achrafmataich.fashion_mnist_backend.grpc.Ai.PredictionReply parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.github.achrafmataich.fashion_mnist_backend.grpc.Ai.PredictionReply parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.github.achrafmataich.fashion_mnist_backend.grpc.Ai.PredictionReply parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static com.github.achrafmataich.fashion_mnist_backend.grpc.Ai.PredictionReply parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.github.achrafmataich.fashion_mnist_backend.grpc.Ai.PredictionReply parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.github.achrafmataich.fashion_mnist_backend.grpc.Ai.PredictionReply parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.github.achrafmataich.fashion_mnist_backend.grpc.Ai.PredictionReply prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ai.PredictionReply}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ai.PredictionReply)
        com.github.achrafmataich.fashion_mnist_backend.grpc.Ai.PredictionReplyOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.github.achrafmataich.fashion_mnist_backend.grpc.Ai.internal_static_ai_PredictionReply_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.github.achrafmataich.fashion_mnist_backend.grpc.Ai.internal_static_ai_PredictionReply_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.github.achrafmataich.fashion_mnist_backend.grpc.Ai.PredictionReply.class, com.github.achrafmataich.fashion_mnist_backend.grpc.Ai.PredictionReply.Builder.class);
      }

      // Construct using ai.Ai.PredictionReply.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        prediction_ = "";
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.github.achrafmataich.fashion_mnist_backend.grpc.Ai.internal_static_ai_PredictionReply_descriptor;
      }

      @java.lang.Override
      public com.github.achrafmataich.fashion_mnist_backend.grpc.Ai.PredictionReply getDefaultInstanceForType() {
        return com.github.achrafmataich.fashion_mnist_backend.grpc.Ai.PredictionReply.getDefaultInstance();
      }

      @java.lang.Override
      public com.github.achrafmataich.fashion_mnist_backend.grpc.Ai.PredictionReply build() {
        com.github.achrafmataich.fashion_mnist_backend.grpc.Ai.PredictionReply result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.github.achrafmataich.fashion_mnist_backend.grpc.Ai.PredictionReply buildPartial() {
        com.github.achrafmataich.fashion_mnist_backend.grpc.Ai.PredictionReply result = new com.github.achrafmataich.fashion_mnist_backend.grpc.Ai.PredictionReply(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(com.github.achrafmataich.fashion_mnist_backend.grpc.Ai.PredictionReply result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.prediction_ = prediction_;
        }
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.github.achrafmataich.fashion_mnist_backend.grpc.Ai.PredictionReply) {
          return mergeFrom((com.github.achrafmataich.fashion_mnist_backend.grpc.Ai.PredictionReply)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.github.achrafmataich.fashion_mnist_backend.grpc.Ai.PredictionReply other) {
        if (other == com.github.achrafmataich.fashion_mnist_backend.grpc.Ai.PredictionReply.getDefaultInstance()) return this;
        if (!other.getPrediction().isEmpty()) {
          prediction_ = other.prediction_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                prediction_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.lang.Object prediction_ = "";
      /**
       * <code>string prediction = 1;</code>
       * @return The prediction.
       */
      public java.lang.String getPrediction() {
        java.lang.Object ref = prediction_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          prediction_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string prediction = 1;</code>
       * @return The bytes for prediction.
       */
      public com.google.protobuf.ByteString
          getPredictionBytes() {
        java.lang.Object ref = prediction_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          prediction_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string prediction = 1;</code>
       * @param value The prediction to set.
       * @return This builder for chaining.
       */
      public Builder setPrediction(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        prediction_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>string prediction = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearPrediction() {
        prediction_ = getDefaultInstance().getPrediction();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>string prediction = 1;</code>
       * @param value The bytes for prediction to set.
       * @return This builder for chaining.
       */
      public Builder setPredictionBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        prediction_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:ai.PredictionReply)
    }

    // @@protoc_insertion_point(class_scope:ai.PredictionReply)
    private static final com.github.achrafmataich.fashion_mnist_backend.grpc.Ai.PredictionReply DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.github.achrafmataich.fashion_mnist_backend.grpc.Ai.PredictionReply();
    }

    public static com.github.achrafmataich.fashion_mnist_backend.grpc.Ai.PredictionReply getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<PredictionReply>
        PARSER = new com.google.protobuf.AbstractParser<PredictionReply>() {
      @java.lang.Override
      public PredictionReply parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<PredictionReply> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<PredictionReply> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.github.achrafmataich.fashion_mnist_backend.grpc.Ai.PredictionReply getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ai_ImageRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ai_ImageRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ai_PredictionReply_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ai_PredictionReply_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\010ai.proto\022\002ai\"\035\n\014ImageRequest\022\r\n\005image\030" +
      "\001 \001(\t\"%\n\017PredictionReply\022\022\n\nprediction\030\001" +
      " \001(\t2J\n\026FashionMNISTPrediction\0220\n\007Predic" +
      "t\022\020.ai.ImageRequest\032\023.ai.PredictionReply" +
      "b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_ai_ImageRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_ai_ImageRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_ai_ImageRequest_descriptor,
        new java.lang.String[] { "Image", });
    internal_static_ai_PredictionReply_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_ai_PredictionReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_ai_PredictionReply_descriptor,
        new java.lang.String[] { "Prediction", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
